### ISSUE TITLE
The Jobs dataset

### ISSUE THREAD

**Issue by liuqidong07** [d909b/perfect_match#5]
Hello, I am doing some expreiments about causal inference. And I find jobs dataset in /perfect_match/data_access/jobs/, so I use them jobs_DW_bin.test.npz and jobs_DW_bin.train.npz. But I find there 17 covariates in your dataset, while ony 8 covarites in raw data(Lalonde dataset). May I ask why.
Thanks a lot!
 Qidong Liu

**Comment by d909b** [comment]
Hi @liuqidong07 
Thank you for your question.

jobs_DW_bin.(test|train).npz are the same preprocessed datasets used in Shalit, J, Sontag, ICML, 2017 (available at https://www.fredjo.com/).

However, unfortunately, their paper does not detail exactly how they preprocessed the original data. My assumption is that the number of covariates increased because they transformed categorical covariates with more than two distinct values into their one-hot encoded representation, since all categorical covariates are binary in the preprocessed dataset.

Please feel free to reach out to the original authors of Shalit, J, Sontag, ICML, 2017 if you require more details into their preprocessing pipeline.

Hope that helps.

**Comment by liuqidong07** [comment]
Thanks for your quick reply! I will ask the original authors you mentiobed.
